<a href="https://colab.research.google.com/github/moneypitak/DWDM21/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

List()
เก็บอะไรก็ได้

*   ลำดับในการเก็บ
*   มีความสำคัญ




In [57]:
list_a = [1,2,3,4,5,6] #เก็บข้อมูลไว้ใน list_a    # [  ] มีชื่อว่า Square brackets

In [58]:
list_a #รันค่าออกมาดู

[1, 2, 3, 4, 5, 6]

In [59]:
list_b = ['ab',2,3.14,list_a] #list สามารถเก็บได้ทุกชนิดได้หมด

In [60]:
list_b #รันค่าออกมาดู

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

In [61]:
list_a[3] #ในคอมจะนับตัวแรกคือตัวที่ 0

4

## indecing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [62]:
list_b[3] #list ตัวที่ 3 ใน list b

[1, 2, 3, 4, 5, 6]

In [63]:
list_b[3][3]  #list ตัวที่ 3 ใน list b แล้วก็ตัวที่ 3 ใน [ ] อีกที

4

In [64]:
list_b[3][4]  #list ตัวที่ 3 ใน list b แล้วก็ตัวที่ 4 ใน [ ] อีกที

5

In [65]:
list_a[6] #เรียก list ตัวที่ไม่ได้อยู่ใน [] จะเอ่อเร่อ

IndexError: ignored

In [66]:
list_a[-1] #index จากตัวด้านหลังตัวสุดท้ายของ list

6

In [67]:
list_a[-4] #index นับจากหลังมาหน้าตัวที่ 4

3

## การสร้าง list()

In [68]:
list_x1 = []  #การสร้าง list แบบที่ 1 
list_x2 = list() #การสร้าง list แบบที่ 2

In [69]:
print(list_x1) #print ทั้ง 2 list จะได้ list ว่าง
print(list_x2)

[]
[]


## เพิ่มสมาชิกเข้าไปใน list ด้วย append()

In [70]:
list_x1.append(2) #ไม่มีอะไรเกิดขึ้นแสดงว่า 2 มันต้องไปปรากฎที่ไหนสักที่หนึ่ง มันถูกแทรกเข้าไปใน list_x1 แล้ว

In [71]:
list_x1 #จะได้ผลออกมา

[2]

In [72]:
list_x1.append(4) #เอา 4 มาแทนใน list_x1
print(list_x1) #ปริ้นค่า list_x1

[2, 4]


In [73]:
list_x1[0] #ตัวที่ 0 คือเลข 2

2

In [74]:
list_x1[-1] #-1 คือดึงตัวให้แสดงออกมาคือตัวหลังตัวแรก

4

In [75]:
list_x2 #จะเป็นช่องว่าง

[]

In [76]:
list_x2.append('ha')  #แทนค่า ha ใน list_x2

In [77]:
list_x2 #แสดงค่า list_x2 ออกมา #ที่ผลรันออกมา 2 ตัวเพราะรัน 2 ครั้ง

['ha']

## ลบสมาชิกจาก list

In [78]:
list_x1.append('ha') # ลบคำว่า ha ออกครั้งนึง

In [79]:
list_x1 #ลองแสดงค่าออกมาดู

[2, 4, 'ha']

In [80]:
list_x1.pop() #ลบค่า x1 ครั้งที่ 1

'ha'

In [81]:
list_x1.pop() #ลบคำว่า ha ออก
print(list_x1) #ผลรันออกมาก็ตะได้แค่ 2 กับ 4

[2]


## len() ตรวจสอบจำนวนสมาชิกของ list

In [82]:
print(list_b) #ปริ้นค่าที่อยู่ใน list_b ออกมา
print(len(list_b)) #ปริ้นจำนวนใน list_b ออกมา

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [83]:
len(list_a) #ปริ้นจำนวนใน list_a ออกมา

6

## String is a list of charactesrs

In [84]:
st_stat = 'Department od Statistics, Faclty od Science ' #เก็บข้อมูลไว้ใน st_stat

In [85]:
st_stat[10] #ดูตัวที่ 10

' '

In [86]:
len(st_stat) #ดูว่ามีความยาวเท่าไหร่

44

List Slicing การเฉือน list :

list [จุดเริ่มต้น(ทึบ) : จุดสุดท้าย (โปร่ง)]

list [ จุดเริ่มต้น (ทึบ) : จุดสุดท้าย (โปร่ง) : step)]

In [87]:
list_a #แสดงค่า list_a

[1, 2, 3, 4, 5, 6]

In [88]:
list_a[2] #แสดงค่าตัวที่ 2 ใน list คือ 3

3

In [89]:
list_a[-3:]  # : เรียกว่า Colon #เอา 3 ตัวสรุดท้ายจากด้านหลัง เพราะมี -

[4, 5, 6]

In [90]:
list_a[1:4] #เริ่มต้นตัวที่ 1 นับไปถึงตัวที่ 4 แต่ไม่เอาตัวที่ 4 เอาแค่ตัวที่ 3 พอ #หลัง colon ไม่ใส่ละไว้ในฐานที่เข้าใจ

[2, 3, 4]

In [91]:
list_a[:4] #เอาคั้งแต่ตัวที่ 0 ถึงตัวที่ 3

[1, 2, 3, 4]

In [92]:
list_a[:] #เอาทุกตัว

[1, 2, 3, 4, 5, 6]

## Step

In [93]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13,] #เก็บค่าไว้ในตัวแปร list_c

In [94]:
list_c[:10:] #เอา 10 ตัวแรก

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [95]:
list_c[:10:2] #กระโดนทีละ 2 ขั้น

[1, 3, 5, 7, 9]

In [96]:
list_c[::-1] #วิ่งมาจากด้านหลัง

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

## range()

In [97]:
range(21) #ในลักษณะ list เริ่ม 0 โปร่งค้าที่ 21 จะได้แค่ 20 ตัว #อาจจะเป็นการวนลูบก็ได้

range(0, 21)

In [98]:
a = list(range(21)) # เก็บตัวแปรไว้ใน a

In [99]:
a #รับค่าออกมาดู

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [100]:
list(range(1,21)) #รันค่าออกดู

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

การบ้านครั้งที่ 2 (เดี่ยว) คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
*   12:30:15
*   13:41:07
*   09:11:50
*   21:30:15
*   03:10:15





In [101]:
#01:02:03 

a = (1*60*60) + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาทีได้ {a} วินาที')

01:02:03 แปลงเป็นวินาทีได้ 3723 วินาที


### ข้อที่ 1 --> 12:30:15

In [102]:
ex_1 = (12*60*60) + (30*60) + 15
print(f'12 นาฬิกา 2 นาที กับอีก 3 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  {ex_1} วินาที')

12 นาฬิกา 2 นาที กับอีก 3 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  45015 วินาที


### ข้อที่ 2 --> 13:41:07

In [103]:
ex_2 = (13*60*60) + (41*60) + 7
print(f'13 นาฬิกา 41 นาที กับอีก 7 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  {ex_2} วินาที')

13 นาฬิกา 41 นาที กับอีก 7 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  49267 วินาที


### ข้อที่ 3 --> 09:11:50

In [104]:
ex_3 = (9*60*60) + (11*60) + 50
print(f'9 นาฬิกา 11 นาที กับอีก 50 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  {ex_3} วินาที')

9 นาฬิกา 11 นาที กับอีก 50 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  33110 วินาที


### ข้อที่ 4 --> 21:30:15

In [105]:
ex_4 = (21*60*60) + (30*60) + 15
print(f'21 นาฬิกา 30 นาที กับอีก 15 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  {ex_4} วินาที')

21 นาฬิกา 30 นาที กับอีก 15 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  77415 วินาที


### ข้อที่ 5 --> 03:10:15

In [106]:
ex_5 = (3*60*60) + (10*60) + 15
print(f' 3 นาฬิกา 10 นาที กับอีก 15 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  {ex_5} วินาที')

 3 นาฬิกา 10 นาที กับอีก 15 วินาที สามารถแปลงเป็นวินาทีได้เท่ากับ -->  11415 วินาที


## Dictionary

*   คล้าย list()
*   Index เป็นอะไรก็ได้




In [107]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # curly

In [108]:
dict_a

{1: 'Happy', '2022': 'Year', 'N': 'New'}

In [109]:
dict_a[1]

'Happy'

In [110]:
dict_a['N']

'New'

In [111]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [112]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

## การเพิ่มสมาชิกลงไปใน Dictionary

In [113]:
dict_a[7] = 3.14

In [114]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [115]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [116]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array

*   เก็บได้แต่ตัวเลข
*   อ้างอิงโดยใช้ พิกัด (2มิติ ก็มองเป็น Matrix)



In [117]:
import numpy

## 1D array

In [118]:
list_A = [1,2,3,4,5]

In [119]:
arr_a = numpy.array(list_A)

In [120]:
arr_a

array([1, 2, 3, 4, 5])

In [121]:
list_A

[1, 2, 3, 4, 5]

In [122]:
arr_a[0]

1

In [123]:
list_A[0]

1

In [124]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [125]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [126]:
arr_b = numpy.array([10,20,30,40,50])

In [127]:
print(arr_a)

[1 2 3 4 5]


In [128]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [129]:
arr_a.shape

(5,)

## 2D array

In [130]:
import numpy as np

In [131]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [132]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
arr2_z.shape

(2, 3)

## np.zeros()

In [134]:
arr2_3_5_0 = np.zeros((3,5))

In [135]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [136]:
arr2_3_5_0[1,2] = 9 #กำหนดค่า

In [137]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [138]:
arr2_3_5_0[1,2] #ชี้

9.0

In [139]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


## np.ones()

In [140]:
arr2_4_5_1 = np.ones((4,5))

In [141]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
arr2_4_5_200 = 200*np.ones((4,5))

In [143]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

## Matrix operations
 การบวก ลบ matrix  บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [144]:
#arr2_4_5_200 + arr2_3_5_0  # การบวก ลบ matrix shape ต้องเท่ากัน

In [145]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

## การคูณ matrix
 scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)

 Matrix คูณ Matrix (แถวคูณหลัก)

In [146]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

 (dot product)

(m,n)  (n,o) = (m,o) (Shape)

In [147]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [148]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [149]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [150]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

## axc, bxc

In [151]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [152]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

## cxa, cxb

In [153]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [154]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [155]:
mat_a * mat_b   # คูณตัวตำแหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

## Matrix Slicing

In [156]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

# HW 3
1.   สร้าง array ที่เป็นรูป ต้น Christmas

2.   slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว



In [162]:
#ข้อ 1

T = np.ones((14,9))
T[1::,4] = 88
T[3:6,3:6] = 88
T[5:7,5:7] = 88
T[5:7,2:7] = 88
T[7:9,1:8] = 88
T[9:12,0:9] = 88
T[12:15,4] = 0

print(T)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. 88.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. 88.  1.  1.  1.  1.]
 [ 1.  1.  1. 88. 88. 88.  1.  1.  1.]
 [ 1.  1.  1. 88. 88. 88.  1.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88.  1.  1.]
 [ 1. 88. 88. 88. 88. 88. 88. 88.  1.]
 [ 1. 88. 88. 88. 88. 88. 88. 88.  1.]
 [88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 1.  1.  1.  1.  0.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  1.  1.  1.  1.]]


In [158]:
#ข้อ2

HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [159]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2::2]