<a href="https://colab.research.google.com/github/moneypitak/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Numpy

   สร้าง Numpy Array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [7]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

# matrix transpose

In [8]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# สร้าง Matrix เริ่มต้น (Zeros,one)

In [9]:
np_z = np.zeros((4,5))

In [10]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

# สร้าง matrix random

In [13]:
np_random = np.random.randn(5,5)
np_random

array([[-1.70612606,  0.24659352,  1.79567049,  0.60342478,  1.90205366],
       [ 0.63583271,  1.30177766, -1.57518776, -0.37226255,  0.96052951],
       [-0.02492494, -0.77208549,  0.70570978,  1.18028936, -0.76733814],
       [-0.27160245, -0.15215841, -0.35294857,  0.3961472 ,  0.55336228],
       [ 0.37639615, -0.03221992, -0.07118283, -1.58143553,  1.57231163]])

In [14]:
2 + (5*np.random.randn(3,3))

array([[ -5.07923708,   1.20726958,   7.7550748 ],
       [  2.70532214,  -1.2221832 , -11.72313965],
       [ -4.23662469,   6.7735267 ,   0.4865269 ]])

In [15]:
np.random.randint(5,11,(4,5))

array([[10,  5,  6, 10,  6],
       [ 9,  5,  7,  9,  5],
       [ 9,  9, 10,  8,  7],
       [10,  8,  6, 10,  6]])

In [16]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
1 + np_a

array([[2, 3, 4],
       [5, 6, 7]])

In [19]:
2 * np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [20]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [21]:
np_a + np_c

array([[7, 7, 7],
       [7, 7, 7]])

In [22]:
np_a.shape

(2, 3)

In [23]:
np_c.shape

(2, 3)

In [24]:
np_c.T.shape

(3, 2)

In [25]:
np.dot(np_a,np_c.T)


array([[28, 10],
       [73, 28]])

In [26]:

np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np_a[1,1]

5

In [28]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [29]:
np_a[0,:]

array([1, 2, 3])

In [30]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.sum(np_a)

21

In [32]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [33]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [34]:
np.mean(np_a)

3.5

In [35]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

In [36]:
np_a.shape

(2, 3)

In [37]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


In [ ]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

วากาเมะ ข้อ 9

วนลูปหาค่า np.min(np.a,axis=0)

In [39]:
np.min(np_a,axis=0)

array([1, 2, 3])

In [40]:
min = np.zeros(np_a.shape[1])

for row in range(np_a.shape[1]):
   min[row] = min(np_a[row])
print(min)

TypeError: ignored